### ISSUE TITLE
Default code in "goes right after" (TS) gives an error

### ISSUE THREAD

**Issue by GusHebblewhite** [CheckiO-Missions/checkio-mission-goes-after#10]
I'm a bit too new to JS/TS know exactly what's going wrong, but the error I get is:
```
10,13: Property 'is_checking' does not exist on type 'Global & typeof globalThis'.
```

This happens when I try to run the code in checkio, and also when i try to run it locally.

https://github.com/CheckiO-Missions/checkio-mission-goes-after/blob/master/editor/initial_code/js_node

**Comment by GusHebblewhite** [comment]
Ditto for the following mission (https://js.checkio.org/mission/time-converter-24h-to-12h/solve/). If I find others, I won't bother to note them for now as I assume one could easily grep the repo for "global.is_checking" or something similar, since this might be a more widespread bug, but let me know if I can help.

**Comment by oduvan** [comment]
Super strange. We will check all missions

**Comment by oduvan** [comment]
Looks like we have this issue for only those two.

Fixed.
