### ISSUE TITLE
bug in tests

### ISSUE THREAD

**Issue by steing** [CheckiO-Missions/checkio-mission-goes-after#4]
taken from test dict...
`{
            "input": ['almaz', 'm', 'a'],
            "answer": False
  },`

i do believe "ma" is in "almaz".

**Comment by oduvan** [comment]
thank you for pointing out. 

I've change the description

**Comment by tnbmorais** [comment]
Don't know if I'm seeing something wrong. 
The `a` is right after the `m` in the word `almaz`.

The assertion should be set to `true`. Or I'm missing something?

**Comment by oduvan** [comment]
@tnbmorais yes https://github.com/CheckiO-Missions/checkio-mission-goes-after/blob/master/info/task_description.html#L10
If more than one symbol is in the list you should always count the first one
