### ISSUE TITLE
Second extra test is not in specification

### ISSUE THREAD

**Issue by MarkRdgOx** [CheckiO-Missions/checkio-mission-goes-after#9]
The test "goes_after('almaz','m','a') == False" is not clearly in the specification.

If this is a correct test, the specification should read: "check if one symbol appears **only** after right after another."

**Comment by oduvan** [comment]
I'm not sure what "only" will change here

**Comment by MarkRdgOx** [comment]
In almaz, "a" does appear right after "m" (in the "ma"). However, it does not appear **only** right after m (because of the starting a)

**Comment by oduvan** [comment]
I see your point. Thank you. I'll change the description
